name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
        - name: Clone codebase
          uses: actions/checkout@v4

        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: 'yarn'

        - name: Install project dependencies
          run: yarn install --prefer-offline

        - name: Lint
          run: yarn lint
